// ══════════════════════════════════════════════
// BANCO DE QUESTÕES — organizadas por tema
// Cada tema tem várias questões; o jogo sorteia
// 8 aleatórias e diferentes a cada partida.
// ══════════════════════════════════════════════
const QUESTION_BANK = {

  select: {
    name: 'SELECT',
    icon: '🔍',
    color: '#3b82f6',
    questions: [
      { desc:"Selecione TODOS os dados da tabela clientes", hint:"Use * para todas as colunas",
        answer:["SELECT","*","FROM","clientes"],
        extra:["WHERE","INSERT","nome","DELETE","INTO","ORDER BY"],
        explain:"SELECT * FROM tabela retorna todas as colunas e linhas." },
      { desc:"Selecione apenas nome e email da tabela usuarios", hint:"Liste colunas separadas por vírgula",
        answer:["SELECT","nome,","email","FROM","usuarios"],
        extra:["*","WHERE","AND","UPDATE","INTO","id"],
        explain:"Listar colunas específicas evita trazer dados desnecessários." },
      { desc:"Selecione produtos onde o preço seja maior que 100", hint:"Use WHERE para filtrar",
        answer:["SELECT","*","FROM","produtos","WHERE","preco",">","100"],
        extra:["HAVING","AND","OR","nome","INSERT","="],
        explain:"WHERE filtra linhas. Operadores: >, <, >=, <=, =, <>" },
      { desc:"Selecione clientes ordenados pelo nome em ordem crescente", hint:"ORDER BY coluna ASC",
        answer:["SELECT","*","FROM","clientes","ORDER BY","nome","ASC"],
        extra:["WHERE","DESC","GROUP BY","HAVING","LIMIT","AND"],
        explain:"ORDER BY ordena resultados. ASC = crescente, DESC = decrescente." },
      { desc:"Selecione os 5 primeiros registros da tabela pedidos", hint:"Use LIMIT para restringir",
        answer:["SELECT","*","FROM","pedidos","LIMIT","5"],
        extra:["ORDER BY","WHERE","TOP","OFFSET","GROUP BY","id"],
        explain:"LIMIT restringe o número de linhas. Muito útil com ORDER BY." },
      { desc:"Selecione nomes únicos da tabela clientes", hint:"DISTINCT elimina duplicatas",
        answer:["SELECT","DISTINCT","nome","FROM","clientes"],
        extra:["*","UNIQUE","WHERE","GROUP BY","ORDER BY","id"],
        explain:"DISTINCT retorna apenas valores únicos, eliminando duplicatas." },
      { desc:"Selecione funcionários de SP com salário acima de 3000", hint:"Use AND para combinar condições",
        answer:["SELECT","*","FROM","funcionarios","WHERE","cidade","=","'SP'","AND","salario",">","3000"],
        extra:["OR","HAVING","IN","BETWEEN","GROUP BY","nome"],
        explain:"AND exige que AMBAS condições sejam verdadeiras." },
      { desc:"Selecione clientes cujo nome começa com a letra A", hint:"Use LIKE com % como curinga",
        answer:["SELECT","*","FROM","clientes","WHERE","nome","LIKE","'A%'"],
        extra:["=","DISTINCT","IN","AND","ORDER BY","id"],
        explain:"LIKE com % substitui qualquer sequência de caracteres." },
      { desc:"Selecione pedidos com valor entre 100 e 500", hint:"BETWEEN inclui os limites",
        answer:["SELECT","*","FROM","pedidos","WHERE","valor","BETWEEN","100","AND","500"],
        extra:[">=","<=","OR","HAVING","LIKE","nome"],
        explain:"BETWEEN é inclusivo nos dois extremos: >= 100 AND <= 500." },
      { desc:"Selecione produtos cujo estoque é NULL", hint:"Para verificar NULL use IS NULL",
        answer:["SELECT","*","FROM","produtos","WHERE","estoque","IS NULL"],
        extra:["=","NULL","LIKE","AND","OR","IS NOT NULL"],
        explain:"Nunca use = NULL; sempre use IS NULL ou IS NOT NULL." },
      { desc:"Selecione os 10 pedidos mais caros em ordem decrescente", hint:"Combine ORDER BY DESC com LIMIT",
        answer:["SELECT","*","FROM","pedidos","ORDER BY","valor","DESC","LIMIT","10"],
        extra:["ASC","WHERE","GROUP BY","HAVING","AND","nome"],
        explain:"ORDER BY + LIMIT é o padrão para 'Top N' no MySQL." },
      { desc:"Selecione clientes de SP ou RJ", hint:"Use IN para lista de valores",
        answer:["SELECT","*","FROM","clientes","WHERE","cidade","IN","('SP','RJ')"],
        extra:["=","AND","OR","LIKE","BETWEEN","DISTINCT"],
        explain:"IN é mais elegante que múltiplos OR para listas de valores." },
    ]
  },

  insert: {
    name: 'INSERT',
    icon: '➕',
    color: '#8b5cf6',
    questions: [
      { desc:"Insira um cliente com nome 'Ana' e idade 25", hint:"INSERT INTO tabela (colunas) VALUES (valores)",
        answer:["INSERT","INTO","clientes","(nome,","idade)","VALUES","('Ana',","25)"],
        extra:["SELECT","FROM","UPDATE","WHERE","SET","DELETE"],
        explain:"INSERT INTO especifica colunas e VALUES fornece os dados." },
      { desc:"Insira um produto com nome 'Notebook' e preço 3500", hint:"Strings precisam de aspas simples",
        answer:["INSERT","INTO","produtos","(nome,","preco)","VALUES","('Notebook',","3500)"],
        extra:["SELECT","FROM","UPDATE","WHERE","DELETE","id"],
        explain:"Valores texto precisam de aspas simples; números não." },
      { desc:"Insira um pedido para o cliente de id 5 com valor 200", hint:"Informe as colunas na mesma ordem dos valores",
        answer:["INSERT","INTO","pedidos","(cliente_id,","valor)","VALUES","(5,","200)"],
        extra:["SELECT","FROM","WHERE","UPDATE","DELETE","SET"],
        explain:"A ordem das colunas deve corresponder exatamente à ordem dos VALUES." },
      { desc:"Insira múltiplos produtos em um único comando", hint:"Separe os grupos de valores por vírgula",
        answer:["INSERT","INTO","produtos","(nome)","VALUES","('Mouse'),","('Teclado'),","('Monitor')"],
        extra:["SELECT","FROM","UPDATE","WHERE","DELETE","AND"],
        explain:"MySQL suporta múltiplos VALUE sets em um único INSERT — mais eficiente." },
      { desc:"Copie clientes inativos para a tabela clientes_backup", hint:"Combine INSERT com SELECT",
        answer:["INSERT","INTO","clientes_backup","SELECT","*","FROM","clientes","WHERE","ativo","=","0"],
        extra:["VALUES","UPDATE","DELETE","AND","ORDER BY","LIMIT"],
        explain:"INSERT INTO ... SELECT copia registros de uma tabela para outra." },
      { desc:"Insira um usuário e ignore se já existir pelo email", hint:"INSERT IGNORE evita erro de chave duplicada",
        answer:["INSERT","IGNORE","INTO","usuarios","(email)","VALUES","('ana@email.com')"],
        extra:["SELECT","FROM","WHERE","UPDATE","DELETE","OR REPLACE"],
        explain:"INSERT IGNORE transforma erros de chave duplicada em warnings silenciosos." },
      { desc:"Insira ou atualize o estoque do produto id=5", hint:"ON DUPLICATE KEY UPDATE faz upsert",
        answer:["INSERT","INTO","estoque","(produto_id,","qtd)","VALUES","(5,","10)","ON DUPLICATE KEY UPDATE","qtd","=","qtd","+","10"],
        extra:["SELECT","WHERE","DELETE","OR IGNORE","SET","FROM"],
        explain:"ON DUPLICATE KEY UPDATE: insere se não existir, atualiza se existir (upsert)." },
      { desc:"Insira um funcionário sem informar o id (auto incremento)", hint:"Omita a coluna AUTO_INCREMENT",
        answer:["INSERT","INTO","funcionarios","(nome,","cargo)","VALUES","('João',","'Dev')"],
        extra:["id,","SELECT","FROM","WHERE","UPDATE","AUTO_INCREMENT"],
        explain:"Colunas AUTO_INCREMENT são preenchidas automaticamente pelo MySQL." },
    ]
  },

  update_delete: {
    name: 'UPDATE / DELETE',
    icon: '✏️',
    color: '#ec4899',
    questions: [
      { desc:"Atualize o email do usuário com id = 3", hint:"UPDATE tabela SET coluna = valor WHERE condição",
        answer:["UPDATE","usuarios","SET","email","=","'novo@email.com'","WHERE","id","=","3"],
        extra:["SELECT","FROM","INSERT","INTO","DELETE","AND"],
        explain:"SEMPRE use WHERE no UPDATE! Sem ele TODOS os registros serão alterados." },
      { desc:"Delete os pedidos com status 'cancelado'", hint:"DELETE FROM tabela WHERE condição",
        answer:["DELETE","FROM","pedidos","WHERE","status","=","'cancelado'"],
        extra:["SELECT","*","TRUNCATE","AND","UPDATE","INTO"],
        explain:"Assim como o UPDATE, nunca esqueça o WHERE no DELETE!" },
      { desc:"Aumente em 10% o salário de todos os desenvolvedores", hint:"SET pode usar expressões matemáticas",
        answer:["UPDATE","funcionarios","SET","salario","=","salario","*","1.1","WHERE","cargo","=","'Dev'"],
        extra:["SELECT","FROM","INSERT","DELETE","AND","OR"],
        explain:"SET aceita expressões: coluna = coluna * 1.1 multiplica o valor atual." },
      { desc:"Esvazie todos os dados da tabela logs sem dropar a tabela", hint:"TRUNCATE é mais rápido que DELETE sem WHERE",
        answer:["TRUNCATE","TABLE","logs"],
        extra:["DELETE","FROM","DROP","WHERE","id",">","0"],
        explain:"TRUNCATE remove todos os dados rapidamente e reinicia o AUTO_INCREMENT." },
      { desc:"Delete clientes que não fizeram pedidos (id não está em pedidos)", hint:"Use NOT IN com subquery",
        answer:["DELETE","FROM","clientes","WHERE","id","NOT IN","(SELECT","cliente_id","FROM","pedidos)"],
        extra:["IN","=","AND","OR","UPDATE","SET"],
        explain:"NOT IN com subquery deleta registros sem correspondência em outra tabela." },
      { desc:"Atualize o status de pedidos mais antigos que 30 dias para 'expirado'", hint:"Use DATE_SUB para calcular data",
        answer:["UPDATE","pedidos","SET","status","=","'expirado'","WHERE","criado_em","<","DATE_SUB(NOW(),","INTERVAL","30","DAY)"],
        extra:["SELECT","FROM","DELETE","INSERT","AND","ORDER BY"],
        explain:"DATE_SUB(NOW(), INTERVAL 30 DAY) calcula a data 30 dias atrás." },
      { desc:"Delete os 10 registros mais antigos da tabela eventos", hint:"Combine ORDER BY com LIMIT no DELETE",
        answer:["DELETE","FROM","eventos","ORDER BY","criado_em","ASC","LIMIT","10"],
        extra:["SELECT","WHERE","TRUNCATE","UPDATE","SET","DESC"],
        explain:"MySQL permite ORDER BY + LIMIT no DELETE para remover registros específicos." },
      { desc:"Atualize nome e email ao mesmo tempo de um usuário", hint:"Separe múltiplos campos com vírgula no SET",
        answer:["UPDATE","usuarios","SET","nome","=","'Maria',","email","=","'maria@mail.com'","WHERE","id","=","1"],
        extra:["SELECT","FROM","INSERT","DELETE","AND","OR"],
        explain:"SET aceita múltiplas colunas separadas por vírgula em um único UPDATE." },
    ]
  },

  ddl: {
    name: 'CREATE / DROP / ALTER',
    icon: '🏗️',
    color: '#10b981',
    questions: [
      { desc:"Crie uma tabela 'produtos' com id INT e nome VARCHAR(100)", hint:"CREATE TABLE nome (colunas)",
        answer:["CREATE","TABLE","produtos","(id","INT,","nome","VARCHAR(100))"],
        extra:["SELECT","DROP","ALTER","FROM","INSERT","PRIMARY"],
        explain:"CREATE TABLE define o nome e as colunas com seus tipos de dados." },
      { desc:"Remova completamente a tabela 'temp_dados'", hint:"DROP TABLE remove dados e estrutura",
        answer:["DROP","TABLE","temp_dados"],
        extra:["DELETE","FROM","TRUNCATE","ALTER","CREATE","IF EXISTS"],
        explain:"DROP TABLE remove a tabela E todos os seus dados permanentemente." },
      { desc:"Adicione uma coluna 'telefone' VARCHAR(20) na tabela clientes", hint:"ALTER TABLE ... ADD COLUMN",
        answer:["ALTER","TABLE","clientes","ADD","COLUMN","telefone","VARCHAR(20)"],
        extra:["MODIFY","DROP","CREATE","SET","INSERT","RENAME"],
        explain:"ALTER TABLE ADD COLUMN adiciona uma nova coluna a uma tabela existente." },
      { desc:"Mude o tipo da coluna 'preco' para DECIMAL(10,2) na tabela produtos", hint:"MODIFY COLUMN altera o tipo",
        answer:["ALTER","TABLE","produtos","MODIFY","COLUMN","preco","DECIMAL(10,2)"],
        extra:["CHANGE","ADD","DROP","CREATE","SET","UPDATE"],
        explain:"MODIFY COLUMN altera tipo/definição sem renomear a coluna." },
      { desc:"Remova a coluna 'obs' da tabela pedidos", hint:"DROP COLUMN remove a coluna",
        answer:["ALTER","TABLE","pedidos","DROP","COLUMN","obs"],
        extra:["MODIFY","ADD","CREATE","TRUNCATE","DELETE","SET"],
        explain:"ALTER TABLE DROP COLUMN remove permanentemente a coluna e seus dados." },
      { desc:"Crie a tabela 'produtos' somente se ela não existir", hint:"IF NOT EXISTS evita erro",
        answer:["CREATE","TABLE","IF NOT EXISTS","produtos","(id","INT,","nome","VARCHAR(100))"],
        extra:["DROP","ALTER","OR REPLACE","TEMPORARY","SELECT","FROM"],
        explain:"IF NOT EXISTS ignora o comando silenciosamente se a tabela já existir." },
      { desc:"Renomeie a tabela 'pedidos' para 'orders'", hint:"RENAME TO na sintaxe do ALTER",
        answer:["ALTER","TABLE","pedidos","RENAME","TO","orders"],
        extra:["DROP","ADD","MODIFY","CREATE","COLUMN","SET"],
        explain:"ALTER TABLE ... RENAME TO renomeia a tabela preservando dados e índices." },
      { desc:"Crie um índice na coluna email da tabela usuarios", hint:"ADD INDEX melhora performance de buscas",
        answer:["ALTER","TABLE","usuarios","ADD","INDEX","idx_email","(email)"],
        extra:["MODIFY","DROP","CREATE","UNIQUE","PRIMARY KEY","COLUMN"],
        explain:"Índices aceleram buscas mas ocupam espaço e custam em INSERT/UPDATE." },
      { desc:"Crie uma tabela temporária com os dados de clientes ativos", hint:"TEMPORARY existe apenas na sessão",
        answer:["CREATE","TEMPORARY","TABLE","clientes_temp","AS","SELECT","*","FROM","clientes","WHERE","ativo","=","1"],
        extra:["DROP","ALTER","INSERT","INTO","AND","OR"],
        explain:"Tabelas TEMPORARY são removidas automaticamente ao encerrar a conexão." },
    ]
  },

  aggregation: {
    name: 'Agregação',
    icon: '📊',
    color: '#f59e0b',
    questions: [
      { desc:"Conte quantos produtos existem na tabela", hint:"Função COUNT(*)",
        answer:["SELECT","COUNT(*)","FROM","produtos"],
        extra:["SUM","AVG","MAX","WHERE","*","GROUP BY","AS total"],
        explain:"COUNT(*) conta todas as linhas. COUNT(coluna) ignora NULLs." },
      { desc:"Conte pedidos agrupados por status", hint:"GROUP BY agrupa linhas iguais",
        answer:["SELECT","status,","COUNT(*)","FROM","pedidos","GROUP BY","status"],
        extra:["ORDER BY","HAVING","WHERE","DISTINCT","SUM(*)","AND"],
        explain:"GROUP BY + COUNT permite ver quantos registros existem em cada categoria." },
      { desc:"Calcule a média de salários da tabela funcionarios", hint:"Função AVG calcula a média",
        answer:["SELECT","AVG(salario)","FROM","funcionarios"],
        extra:["SUM(salario)","MAX(salario)","COUNT(*)","WHERE","GROUP BY","AS media"],
        explain:"AVG(coluna) retorna a média aritmética. Outras: SUM, MAX, MIN, COUNT." },
      { desc:"Selecione departamentos com mais de 5 funcionários", hint:"Filtre grupos com HAVING",
        answer:["SELECT","dept,","COUNT(*)","FROM","funcionarios","GROUP BY","dept","HAVING","COUNT(*)",">","5"],
        extra:["WHERE","ORDER BY","DISTINCT","SUM(*)","AND","="],
        explain:"HAVING filtra grupos; WHERE não aceita funções de agregação." },
      { desc:"Encontre o maior e o menor salário da empresa", hint:"MAX e MIN retornam extremos",
        answer:["SELECT","MAX(salario),","MIN(salario)","FROM","funcionarios"],
        extra:["AVG(salario)","COUNT(*)","WHERE","GROUP BY","AS","SUM"],
        explain:"MAX e MIN retornam o maior e menor valor de uma coluna numérica." },
      { desc:"Some o total de vendas por mês", hint:"Combine SUM com GROUP BY",
        answer:["SELECT","mes,","SUM(valor)","FROM","vendas","GROUP BY","mes"],
        extra:["COUNT(*)","AVG(valor)","WHERE","ORDER BY","HAVING","DISTINCT"],
        explain:"SUM + GROUP BY é o padrão para totalizar valores por categoria." },
      { desc:"Mostre departamentos com salário médio acima de 5000 ordenados", hint:"HAVING + ORDER BY",
        answer:["SELECT","dept,","AVG(salario)","AS","media","FROM","funcionarios","GROUP BY","dept","HAVING","AVG(salario)",">","5000","ORDER BY","media","DESC"],
        extra:["WHERE","COUNT(*)","DISTINCT","LIMIT","AND","MIN"],
        explain:"HAVING filtra grupos após agregação; ORDER BY ordena o resultado final." },
      { desc:"Conte clientes distintos que fizeram pedidos", hint:"COUNT com DISTINCT",
        answer:["SELECT","COUNT(DISTINCT","cliente_id)","FROM","pedidos"],
        extra:["*","SUM","AVG","WHERE","GROUP BY","MAX"],
        explain:"COUNT(DISTINCT col) conta valores únicos, ignorando repetições." },
    ]
  },

  joins: {
    name: 'JOIN',
    icon: '🔗',
    color: '#06b6d4',
    questions: [
      { desc:"Faça um INNER JOIN entre pedidos e clientes pelo cliente_id", hint:"ON especifica a condição de junção",
        answer:["SELECT","*","FROM","pedidos","INNER JOIN","clientes","ON","pedidos.cliente_id","=","clientes.id"],
        extra:["LEFT JOIN","WHERE","GROUP BY","HAVING","AND","AS"],
        explain:"INNER JOIN retorna apenas registros com correspondência nas duas tabelas." },
      { desc:"Mostre todos os clientes e seus pedidos (mesmo sem pedido)", hint:"LEFT JOIN inclui todos da esquerda",
        answer:["SELECT","*","FROM","clientes","LEFT JOIN","pedidos","ON","clientes.id","=","pedidos.cliente_id"],
        extra:["INNER JOIN","WHERE","GROUP BY","AND","AS","HAVING"],
        explain:"LEFT JOIN: todos da tabela esquerda + correspondências da direita (NULL se não houver)." },
      { desc:"Mostre nome do cliente e nome do produto de cada pedido", hint:"Use alias nas tabelas para simplificar",
        answer:["SELECT","c.nome,","p.nome","FROM","clientes","c","INNER JOIN","pedidos","pd","ON","c.id","=","pd.cliente_id","INNER JOIN","produtos","p","ON","pd.produto_id","=","p.id"],
        extra:["LEFT JOIN","WHERE","GROUP BY","AS","AND","HAVING"],
        explain:"Múltiplos JOINs encadeados permitem unir 3 ou mais tabelas." },
      { desc:"Encontre clientes que NUNCA fizeram pedidos", hint:"LEFT JOIN + WHERE IS NULL filtra não-correspondências",
        answer:["SELECT","c.nome","FROM","clientes","c","LEFT JOIN","pedidos","p","ON","c.id","=","p.cliente_id","WHERE","p.id","IS NULL"],
        extra:["INNER JOIN","AND","OR","IS NOT NULL","HAVING","GROUP BY"],
        explain:"LEFT JOIN + WHERE coluna_direita IS NULL = registros sem correspondência (anti-join)." },
      { desc:"Conte quantos pedidos cada cliente fez usando JOIN", hint:"Combine JOIN com GROUP BY e COUNT",
        answer:["SELECT","c.nome,","COUNT(p.id)","AS","total","FROM","clientes","c","LEFT JOIN","pedidos","p","ON","c.id","=","p.cliente_id","GROUP BY","c.id"],
        extra:["INNER JOIN","HAVING","ORDER BY","SUM","WHERE","DISTINCT"],
        explain:"JOIN + GROUP BY + COUNT é o padrão para contar registros relacionados." },
      { desc:"Selecione pedidos com valor acima de 500 incluindo nome do cliente", hint:"Pode filtrar com WHERE após o JOIN",
        answer:["SELECT","c.nome,","p.valor","FROM","pedidos","p","INNER JOIN","clientes","c","ON","p.cliente_id","=","c.id","WHERE","p.valor",">","500"],
        extra:["LEFT JOIN","GROUP BY","HAVING","ORDER BY","AND","DISTINCT"],
        explain:"WHERE após JOIN filtra o resultado combinado das duas tabelas." },
    ]
  },

  constraints: {
    name: 'Constraints',
    icon: '🔒',
    color: '#10b981',
    questions: [
      { desc:"Crie tabela 'usuarios' com id como chave primária auto incremento", hint:"PRIMARY KEY + AUTO_INCREMENT",
        answer:["CREATE","TABLE","usuarios","(id","INT","AUTO_INCREMENT","PRIMARY KEY,","nome","VARCHAR(100))"],
        extra:["UNIQUE","NOT NULL","FOREIGN KEY","DEFAULT","INDEX","CHECK"],
        explain:"PRIMARY KEY garante unicidade e NOT NULL. AUTO_INCREMENT gera o valor automaticamente." },
      { desc:"Adicione UNIQUE constraint na coluna email da tabela usuarios", hint:"UNIQUE impede valores duplicados",
        answer:["ALTER","TABLE","usuarios","ADD","CONSTRAINT","uk_email","UNIQUE","(email)"],
        extra:["PRIMARY KEY","FOREIGN KEY","NOT NULL","INDEX","CHECK","DEFAULT"],
        explain:"UNIQUE garante que não haverá dois registros com o mesmo valor na coluna." },
      { desc:"Adicione uma FK de pedidos referenciando clientes com CASCADE", hint:"FOREIGN KEY ... REFERENCES ... ON DELETE CASCADE",
        answer:["ALTER","TABLE","pedidos","ADD","CONSTRAINT","fk_cliente","FOREIGN KEY","(cliente_id)","REFERENCES","clientes(id)","ON DELETE CASCADE"],
        extra:["UNIQUE","NOT NULL","PRIMARY KEY","SET NULL","RESTRICT","INDEX"],
        explain:"ON DELETE CASCADE apaga automaticamente os pedidos quando o cliente é deletado." },
      { desc:"Adicione valor padrão 'ativo' para a coluna status", hint:"DEFAULT define o valor automático",
        answer:["ALTER","TABLE","clientes","ALTER","COLUMN","status","SET","DEFAULT","'ativo'"],
        extra:["ADD","MODIFY","NOT NULL","UNIQUE","PRIMARY KEY","CHECK"],
        explain:"DEFAULT define o valor usado quando a coluna não é informada no INSERT." },
      { desc:"Crie uma tabela com CHECK para garantir que idade >= 18", hint:"CHECK valida condição lógica",
        answer:["CREATE","TABLE","adultos","(id","INT,","nome","VARCHAR(100),","idade","INT,","CHECK","(idade",">=","18))"],
        extra:["UNIQUE","NOT NULL","DEFAULT","FOREIGN KEY","PRIMARY KEY","AUTO_INCREMENT"],
        explain:"CHECK valida uma expressão. Se falsa, o INSERT/UPDATE falha. Disponível desde MySQL 8.0.16." },
      { desc:"Remova a foreign key chamada fk_dept da tabela funcionarios", hint:"DROP FOREIGN KEY remove a constraint",
        answer:["ALTER","TABLE","funcionarios","DROP","FOREIGN KEY","fk_dept"],
        extra:["DROP COLUMN","DROP INDEX","MODIFY","ADD","PRIMARY KEY","UNIQUE"],
        explain:"Para remover FK use DROP FOREIGN KEY nome. Para índices, DROP INDEX nome." },
    ]
  },
};

// Retorna N questões aleatórias de um tema (sem repetição)
function getRandomQuestions(themeKeys, count = 8) {
  let pool = [];
  themeKeys.forEach(key => {
    if (QUESTION_BANK[key]) {
      QUESTION_BANK[key].questions.forEach(q => pool.push({ ...q, theme: key }));
    }
  });
  // Fisher-Yates shuffle
  for (let i = pool.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [pool[i], pool[j]] = [pool[j], pool[i]];
  }
  return pool.slice(0, Math.min(count, pool.length));
}
